services:
  - type: web
    name: crypto-price-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app:app
    pythonVersion: 3.10.13
